### Test creating a new faculty
POST http://localhost:3000/faculty-api/
Content-Type: application/json

{
  "facultyId": "001A04",
  "name": "John DOe",
  "email": "john@example.com",
  "department": "Computer Science",
  "dateOfJoining": "2019-11-18"
}

### Test retrieving all faculties
GET http://localhost:3000/faculty-api/

### Get faculty by ID
GET http://localhost:3000/faculty-api/68059bb7be95c98ad74d3c9e

### Test updating a faculty
PUT http://localhost:3000/faculty-api/68059bb7be95c98ad74d3c9e
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@example.com",
  "department": "Mathematics"
}

### Test soft-deleting a faculty
PUT http://localhost:3000/faculty-api/delete/68036a0e341105ab09630d9f
Content-Type: application/json

{
  "isActive": false
}



### post new timetable record
POST http://localhost:3000/tt-api/add 
Content-Type: application/json

{
  "facultyId": "001A04",
  "facultyName": "John",
  "timetable": {
    "Thursday": [
      {
        "period": 2,
        "subject": "chemistry",
        "time": "11:00 - 12:00",
        "year": 1,
        "branch": "CSE-D"
      }
    ],
    "Friday": [
      {
        "period": 1,
        "subject": "EVS",
        "time": "10:00 - 1:00",
        "year": 1,
        "branch": "CSE-D"
      }
    ]
  }
}


### Get all timetables
GET http://localhost:3000/tt-api/timetables


### get timetable of specific faculty
GET http://localhost:3000/tt-api/timetable/68059bb7be95c98ad74d3c9e

### Update a timetable
PUT http://localhost:3000/tt-api/update/68039b7d76446609f71ebfd7
Content-Type: application/json

{
  "timetable":{
    "Monday":[{
      "period":2,
      "subject":"chemistry",
      "time":"11:00 - 12:00",
      "year": 1,
      "branch": "CSE-D"
    }],
    "Tuesday":[{
      "period":1,
      "subject":"EVS",
      "time":"10:00 - 11:00",
      "year": 1,
      "branch": "CSE-D"
    }]
  }
}


### delete a timetable record
DELETE  http://localhost:3000/tt-api/delete/68039c84306ad90b50a81cfc
